name: dummy
base: core24
summary: A dummy app
grade: stable
confinement: classic
contact: https://github.com/nscloud-demo/snapcraft-repro/discussions
issues: https://github.com/nscloud-demo/snapcraft-repro/issues
website: https://namespace.so/
adopt-info: dummy
version: dev
description: |
  This is a dummy app to reproduce an issue with Snapcraft build in Namespace Ubuntu environment.

parts:
  dummy:
    source: .
    plugin: nil
    override-build: |
      echo "this is a build"