on: [workflow_dispatch]

name: dummy-build

jobs:
  namespace-amd64:
    runs-on:
      - nscloud-ubuntu-24.04-systemd-amd64-4x16
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - run: |
      #     # based on https://github.com/canonical/lxd-pkg-snap/pull/789/files
      #     _LXD_SNAP_DEVCGROUP_CONFIG="/var/lib/snapd/cgroup/snap.lxd.device"
      #     sudo mkdir -p /var/lib/snapd/cgroup
      #     echo 'self-managed=true' | sudo tee  "${_LXD_SNAP_DEVCGROUP_CONFIG}"
          
      - uses: snapcore/action-build@v1

      - name: Breakpoint on failure
        if: failure() 
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 15m
          authorized-users: edganiukov,hugosantos,n-g,htr,nichtverstehen,gmichelo,pavolmarko

  github-amd64:
    runs-on:
      - ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: snapcore/action-build@v1

      - name: Breakpoint on failure
        if: failure() 
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 15m
          authorized-users: edganiukov,hugosantos,n-g,htr,nichtverstehen,gmichelo,pavolmarko
