on: [workflow_dispatch]

name: dummy-build

jobs:
  namespace-amd64:
    runs-on:
      - nscloud-ubuntu-24.04-systemd-amd64-4x16
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: snapcore/action-build@v1

  github-amd64:
    runs-on:
      - ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: snapcore/action-build@v1
